/*
 * Copyright 2024 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name GPIO_21 (coord H4), ENET_RST
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_RST_PERIPHERAL GPIO                    /*!<@brief Peripheral name */
#define BOARD_INITPINS_ENET_RST_SIGNAL PIO0                        /*!<@brief Signal name */
#define BOARD_INITPINS_ENET_RST_CHANNEL 21                         /*!<@brief Signal channel */
#define BOARD_INITPINS_ENET_RST_GPIO GPIO                          /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_ENET_RST_GPIO_PIN 21U                       /*!<@brief GPIO pin number */
#define BOARD_INITPINS_ENET_RST_PORT 0U                            /*!<@brief PORT number */
#define BOARD_INITPINS_ENET_RST_PIN 21U                            /*!<@brief PORT pin number */
#define BOARD_INITPINS_ENET_RST_PIN_MASK (1U << 21U)               /*!<@brief PORT pin mask */
                                                                   /* @} */

/*! @name GPIO_55 (coord K6), ENET_INT
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_INT_PERIPHERAL GPIO                   /*!<@brief Peripheral name */
#define BOARD_INITPINS_ENET_INT_SIGNAL PIO1                       /*!<@brief Signal name */
#define BOARD_INITPINS_ENET_INT_CHANNEL 23                        /*!<@brief Signal channel */
#define BOARD_INITPINS_ENET_INT_GPIO GPIO                         /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_ENET_INT_GPIO_PIN 55U                      /*!<@brief GPIO pin number */
#define BOARD_INITPINS_ENET_INT_PORT 1U                           /*!<@brief PORT number */
#define BOARD_INITPINS_ENET_INT_PIN 23U                           /*!<@brief PORT pin number */
#define BOARD_INITPINS_ENET_INT_PIN_MASK (1U << 23U)              /*!<@brief PORT pin mask */
                                                                  /* @} */

/*!
 * @brief 
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M33 */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
